query Search(
    $query: String!,
    $first: Int!,
    $after: String,
    $filters: [ProductFilter!],
    $sortKey: SearchSortKeys,
    $reverse: Boolean
) {
    search(
        query: $query,
        first: $first,
        after: $after,
        types: [PRODUCT, PAGE, ARTICLE],
        unavailableProducts: LAST,
        productFilters: $filters,
        prefix: LAST,
        sortKey: $sortKey,
        reverse: $reverse
    ) {
        totalCount
        productFilters {
            id
            label
            type
            values {
                id
                label
                count
                input
            }
        }
        nodes {
            ... on Product {
                id
                title
                handle
                vendor
                productType
                tags
                options(first: 10) {
                    name
                    values
                }
                featuredImage {
                    url
                    altText
                }
                priceRange {
                    minVariantPrice {
                        amount
                        currencyCode
                    }
                }
            }
            ... on Article {
                id
                title
                handle
                excerpt
                image {
                    url
                    altText
                }
            }
            ... on Page {
                id
                title
                handle
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
