query GetProductById($id: ID!) {
    product(id: $id) {
        id
        title
        handle
        descriptionHtml
        description
        tags
        availableForSale
        productType
        vendor
        category {
            id
            name
        }
        media(first: 10)  {
            nodes {
                id
                alt
                mediaContentType
                previewImage {
                    altText
                    url
                }
            }
        }
        featuredImage {
            url
            altText
        }
        images(first: 10) { edges { node { url altText width height } } }
        options {
            id
            name
            optionValues {
                name
                swatch {
                    color
                    image {
                        alt
                        previewImage {
                            altText
                            url
                        }
                    }
                }
            }

        }
        variants(first: 25) {
            edges {
                node {
                    id
                    title
                    sku
                    availableForSale
                    quantityAvailable
                    requiresShipping
                    selectedOptions { name value }
                    price { amount currencyCode }
                    compareAtPrice { amount currencyCode }
                    image { url altText }
                    product {
                        id
                    }
                }
            }
        }
        priceRange {
            minVariantPrice { amount currencyCode }
            maxVariantPrice { amount currencyCode }
        }
        seo { title description }
        reviewsMetafield: metafield(namespace: "marketak", key: "items") {
            references(first: 50) {
                nodes {
                    ... on Metaobject {
                        id
                        type
                        updatedAt
                        customerId: field(key: "customer_id") { value }
                        customerName: field(key: "customer_name") { value }
                        rating: field(key: "rating") { value }
                        title: field(key: "title") { value }
                        body: field(key: "body") { value }
                        createdAt: field(key: "created_at") { value }
                        approved: field(key: "approved") { value }
                    }
                }
            }
        }
    }
}
