query PredictiveSearch($query: String!) {
    predictiveSearch(
        query: $query,
        limit: 5,
        limitScope: EACH,
        types: [PRODUCT, COLLECTION, PAGE, ARTICLE, QUERY],
        unavailableProducts: LAST
    ) {
        products {
            id
            title
            handle
            featuredImage {
                url
                altText
            }
            priceRange {
                minVariantPrice {
                    amount
                    currencyCode
                }
            }
        }
        collections {
            id
            title
            handle
            image {
                url
                altText
            }
        }
        articles {
            id
            title
            handle
            image {
                url
                altText
            }
        }
        pages {
            id
            title
            handle
        }
        queries {
            text
            styledText
            trackingParameters
        }
    }
}